#!/bin/bash
DEBIAN_ARCH="${DEBIAN_ARCH:-$(dpkg --print-architecture)}"
debian/build "$(cat monolith/v8version)" -a"$DEBIAN_ARCH"
mv "../v8dmoj_$(cat monolith/v8version)_$DEBIAN_ARCH.deb" .
rm "../v8dmoj_$(cat monolith/v8version)"*
