#!/bin/sh
if [ -z "$1" ]; then
    echo 'Usage: debian/build <version>'
    exit 1
fi

cat > debian/changelog <<EOF
v8dmoj ($1) stable; urgency=medium

  * Updated v8 to $1

 -- Quantum <quantum@dmoj.ca>  $(LC_ALL=C date '+%a, %d %b %Y %H:%M:%S %z')
EOF

exec dpkg-buildpackage -us -uc -b
